package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.TS;

import greendao.TSDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tSDaoConfig;

    private final TSDao tSDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tSDaoConfig = daoConfigMap.get(TSDao.class).clone();
        tSDaoConfig.initIdentityScope(type);

        tSDao = new TSDao(tSDaoConfig, this);

        registerDao(TS.class, tSDao);
    }
    
    public void clear() {
        tSDaoConfig.getIdentityScope().clear();
    }

    public TSDao getTSDao() {
        return tSDao;
    }

}
