package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table _tl_time_schedule.
 */
public class TSBox {

    private Long id;
    private Boolean b_finish;
    private String s_title;
    private Integer i_status;
    private String s_notice;
    private String s_start_time;
    private String s_end_time;
    private Boolean b_alarm;

    public TSBox() {
    }

    public TSBox(Long id) {
        this.id = id;
    }

    public TSBox(Long id, Boolean b_finish, String s_title, Integer i_status, String s_notice, String s_start_time, String s_end_time, Boolean b_alarm) {
        this.id = id;
        this.b_finish = b_finish;
        this.s_title = s_title;
        this.i_status = i_status;
        this.s_notice = s_notice;
        this.s_start_time = s_start_time;
        this.s_end_time = s_end_time;
        this.b_alarm = b_alarm;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getB_finish() {
        return b_finish;
    }

    public void setB_finish(Boolean b_finish) {
        this.b_finish = b_finish;
    }

    public String getS_title() {
        return s_title;
    }

    public void setS_title(String s_title) {
        this.s_title = s_title;
    }

    public Integer getI_status() {
        return i_status;
    }

    public void setI_status(Integer i_status) {
        this.i_status = i_status;
    }

    public String getS_notice() {
        return s_notice;
    }

    public void setS_notice(String s_notice) {
        this.s_notice = s_notice;
    }

    public String getS_start_time() {
        return s_start_time;
    }

    public void setS_start_time(String s_start_time) {
        this.s_start_time = s_start_time;
    }

    public String getS_end_time() {
        return s_end_time;
    }

    public void setS_end_time(String s_end_time) {
        this.s_end_time = s_end_time;
    }

    public Boolean getB_alarm() {
        return b_alarm;
    }

    public void setB_alarm(Boolean b_alarm) {
        this.b_alarm = b_alarm;
    }

    @Override
    public String toString() {
        return "TSBox, id = " + id
                + "; title = " + s_title
                + "; comment = " + s_notice
                + "; level = " + i_status
                + "; finish = " + b_finish
                + "; s_start_time = " + s_start_time
                + "; end_time = " + s_end_time
                + "; b_alarm = " + b_alarm;
    }

}
