package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table _tl_time_schedule.
 */
public class TSBox {

    private Long id;
    private Boolean b_finish;
    private String s_title;
    private Integer i_status;
    private String s_start_time;

    public TSBox() {
    }

    public TSBox(Long id) {
        this.id = id;
    }

    public TSBox(Long id, Boolean b_finish, String s_title, Integer i_status, String s_start_time) {
        this.id = id;
        this.b_finish = b_finish;
        this.s_title = s_title;
        this.i_status = i_status;
        this.s_start_time = s_start_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getB_finish() {
        return b_finish;
    }

    public void setB_finish(Boolean b_finish) {
        this.b_finish = b_finish;
    }

    public String getS_title() {
        return s_title;
    }

    public void setS_title(String s_title) {
        this.s_title = s_title;
    }

    public Integer getI_status() {
        return i_status;
    }

    public void setI_status(Integer i_status) {
        this.i_status = i_status;
    }

    public String getS_start_time() {
        return s_start_time;
    }

    public void setS_start_time(String s_start_time) {
        this.s_start_time = s_start_time;
    }

}
