package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.TSBox;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table _tl_time_schedule.
*/
public class TSBoxDao extends AbstractDao<TSBox, Long> {

    public static final String TABLENAME = "_tl_time_schedule";

    /**
     * Properties of entity TSBox.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property B_finish = new Property(1, Boolean.class, "b_finish", false, "B_FINISH");
        public final static Property S_title = new Property(2, String.class, "s_title", false, "S_TITLE");
        public final static Property I_status = new Property(3, Integer.class, "i_status", false, "I_STATUS");
        public final static Property S_notice = new Property(4, String.class, "s_notice", false, "S_NOTICE");
        public final static Property S_start_time = new Property(5, String.class, "s_start_time", false, "S_START_TIME");
        public final static Property S_end_time = new Property(6, String.class, "s_end_time", false, "S_END_TIME");
        public final static Property B_alarm = new Property(7, Boolean.class, "b_alarm", false, "B_ALARM");
    };


    public TSBoxDao(DaoConfig config) {
        super(config);
    }
    
    public TSBoxDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'_tl_time_schedule' (" + //
                "'ID' INTEGER PRIMARY KEY ," + // 0: id
                "'B_FINISH' INTEGER," + // 1: b_finish
                "'S_TITLE' TEXT," + // 2: s_title
                "'I_STATUS' INTEGER," + // 3: i_status
                "'S_NOTICE' TEXT," + // 4: s_notice
                "'S_START_TIME' TEXT," + // 5: s_start_time
                "'S_END_TIME' TEXT," + // 6: s_end_time
                "'B_ALARM' INTEGER);"); // 7: b_alarm
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX__tl_time_schedule_ID ON _tl_time_schedule" +
                " (ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'_tl_time_schedule'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TSBox entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Boolean b_finish = entity.getB_finish();
        if (b_finish != null) {
            stmt.bindLong(2, b_finish ? 1l: 0l);
        }
 
        String s_title = entity.getS_title();
        if (s_title != null) {
            stmt.bindString(3, s_title);
        }
 
        Integer i_status = entity.getI_status();
        if (i_status != null) {
            stmt.bindLong(4, i_status);
        }
 
        String s_notice = entity.getS_notice();
        if (s_notice != null) {
            stmt.bindString(5, s_notice);
        }
 
        String s_start_time = entity.getS_start_time();
        if (s_start_time != null) {
            stmt.bindString(6, s_start_time);
        }
 
        String s_end_time = entity.getS_end_time();
        if (s_end_time != null) {
            stmt.bindString(7, s_end_time);
        }
 
        Boolean b_alarm = entity.getB_alarm();
        if (b_alarm != null) {
            stmt.bindLong(8, b_alarm ? 1l: 0l);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TSBox readEntity(Cursor cursor, int offset) {
        TSBox entity = new TSBox( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0, // b_finish
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // s_title
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // i_status
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // s_notice
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // s_start_time
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // s_end_time
            cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0 // b_alarm
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TSBox entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setB_finish(cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0);
        entity.setS_title(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setI_status(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setS_notice(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setS_start_time(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setS_end_time(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setB_alarm(cursor.isNull(offset + 7) ? null : cursor.getShort(offset + 7) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TSBox entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TSBox entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
